language: node_js
node_js:
  - "7.2.1"
install:
  - npm install
script:
  - npm run test
  - npm run build
env:
  - NODE_ENV=production
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  app: cssfp
  api_key:
    secure: "6a69b3d7-62c5-4c26-9049-ab33bbd6f24e"